"""Shared service identities for monitoring and SSH management. No host data."""

SERVICE_CATALOG = [{'name': 'mtproto-proxy',
  'display_name': 'MTProto Proxy',
  'group': 'proxy',
  'unit_candidates': ['mtproto-proxy'],
  'hint': 'scripts/install_mtproto.sh',
  'control_component': 'mtproto'},
 {'name': 'xray',
  'display_name': 'Xray (VLESS-Reality)',
  'group': 'proxy',
  'unit_candidates': ['xray'],
  'hint': 'установка Xray, затем /xray_apply в боте',
  'control_component': 'vless'},
 {'name': 'sing-box',
  'display_name': 'Sing-box',
  'group': 'proxy',
  'unit_candidates': ['sing-box', 'singbox'],
  'hint': 'обычно клиент; на VPS unit sing-box не обязателен',
  'control_component': 'singbox'},
 {'name': 'hysteria',
  'display_name': 'Hysteria2',
  'group': 'proxy',
  'unit_candidates': ['hysteria-server', 'hysteria'],
  'hint': 'scripts/install_hysteria2.sh',
  'control_component': 'hysteria2'},
 {'name': 'naiveproxy',
  'display_name': 'NaiveProxy (Caddy)',
  'group': 'proxy',
  'unit_candidates': ['caddy-naive', 'naiveproxy', 'naive'],
  'hint': 'scripts/install_naiveproxy.sh',
  'control_component': 'naiveproxy'},
 {'name': 'mita',
  'display_name': 'Mieru (mita)',
  'group': 'proxy',
  'unit_candidates': ['mita'],
  'hint': 'scripts/install_mieru.sh',
  'control_component': 'mieru'},
 {'name': 'tailscaled',
  'display_name': 'Tailscale (mesh)',
  'group': 'proxy',
  'unit_candidates': ['tailscaled', 'tailscale'],
  'hint': 'curl -fsSL https://tailscale.com/install.sh | sh',
  'control_component': 'tailscale'},
 {'name': 'telegramonly',
  'display_name': 'TelegramOnly бот/API',
  'group': 'telegramonly',
  'unit_candidates': ['telegramonly'],
  'hint': 'scripts/install_telegramonly_vps.sh',
  'control_component': 'bot'},
 {'name': 'ha-reticulum-bridge',
  'display_name': 'HA Reticulum мост',
  'group': 'telegramonly',
  'unit_candidates': ['ha-reticulum-bridge'],
  'hint': 'scripts/install_ha_stack.sh',
  'control_component': 'reticulum'},
 {'name': 'ha-stub-grpc',
  'display_name': 'HA stub gRPC',
  'group': 'telegramonly',
  'unit_candidates': ['ha-stub-grpc'],
  'hint': 'scripts/install_ha_stack.sh',
  'control_component': 'ha'},
 {'name': 'ha-stub-udp',
  'display_name': 'HA stub UDP',
  'group': 'telegramonly',
  'unit_candidates': ['ha-stub-udp'],
  'hint': 'scripts/install_ha_stack.sh',
  'control_component': 'ha'},
 {'name': 'ha-adapter-grpc',
  'display_name': 'HA adapter gRPC',
  'group': 'telegramonly',
  'unit_candidates': ['ha-adapter-grpc'],
  'hint': 'scripts/install_ha_adapter.sh',
  'control_component': 'ha'},
 {'name': 'ha-rns-watchdog',
  'display_name': 'HA RNS watchdog',
  'group': 'telegramonly',
  'unit_candidates': ['ha-rns-watchdog'],
  'hint': 'ставится вместе с scripts/install_ha_stack.sh',
  'control_component': 'ha'},
 {'name': 'shskm-remote-cli',
  'display_name': 'SHSK-M Remote CLI',
  'group': 'telegramonly',
  'unit_candidates': ['shskm-remote-cli'],
  'hint': 'опционально, unit shskm-remote-cli',
  'control_component': 'shskm'},
 {'name': 'i2pd',
  'display_name': 'i2pd (I2P для Reticulum)',
  'group': 'telegramonly',
  'unit_candidates': ['i2pd'],
  'hint': 'scripts/install_i2p_bridge.sh',
  'control_component': 'i2p'},
 {'name': 'nginx',
  'display_name': 'Nginx',
  'group': 'system',
  'unit_candidates': ['nginx'],
  'control_component': 'nginx'},
 {'name': 'apache2',
  'display_name': 'Apache',
  'group': 'system',
  'unit_candidates': ['apache2'],
  'control_component': None},
 {'name': 'ssh',
  'display_name': 'OpenSSH',
  'group': 'system',
  'unit_candidates': ['ssh', 'sshd'],
  'control_component': None},
 {'name': 'postgresql',
  'display_name': 'PostgreSQL',
  'group': 'system',
  'unit_candidates': ['postgresql'],
  'control_component': None},
 {'name': 'mysql',
  'display_name': 'MySQL',
  'group': 'system',
  'unit_candidates': ['mysql', 'mariadb'],
  'control_component': None},
 {'name': 'docker',
  'display_name': 'Docker',
  'group': 'system',
  'unit_candidates': ['docker'],
  'control_component': None},
 {'name': 'redis-server',
  'display_name': 'Redis',
  'group': 'system',
  'unit_candidates': ['redis-server'],
  'control_component': None},
 {'name': 'tuic',
  'display_name': 'TUIC',
  'group': 'proxy',
  'unit_candidates': ['tuic', 'tuic-server'],
  'control_component': 'tuic'},
 {'name': 'anytls',
  'display_name': 'AnyTLS',
  'group': 'proxy',
  'unit_candidates': ['anytls', 'anytls-server'],
  'control_component': 'anytls'},
 {'name': 'xhttp',
  'display_name': 'XHTTP',
  'group': 'proxy',
  'unit_candidates': ['xhttp', 'xhttp-server'],
  'control_component': 'xhttp'},
 {'name': 'xui',
  'display_name': '3x-ui',
  'group': 'proxy',
  'unit_candidates': ['x-ui'],
  'control_component': 'xui'},
 {'name': 'headscale',
  'display_name': 'Headscale',
  'group': 'proxy',
  'unit_candidates': ['headscale'],
  'control_component': 'headscale'},
 {'name': 'headplane',
  'display_name': 'Headplane',
  'group': 'proxy',
  'unit_candidates': ['headplane'],
  'control_component': 'headplane'}]

CONTAINER_ALIASES = {
    'vless': ('xray',), 'hysteria2': ('hysteria', 'hysteria2'),
    'naiveproxy': ('caddy-naive', 'naiveproxy'), 'mieru': ('mita', 'mieru'),
    'mtproto': ('mtproto-proxy', 'mtproto'), 'tuic': ('tuic', 'tuic-server'),
    'anytls': ('anytls', 'anytls-server'), 'xhttp': ('xhttp', 'xhttp-server'),
    'xui': ('x-ui', '3x-ui'), 'headscale': ('headscale',), 'headplane': ('headplane',),
    'tailscale': ('tailscale', 'tailscaled'), 'reticulum': ('reticulum',),
    'i2p': ('i2pd',), 'nginx': ('nginx',), 'singbox': ('sing-box', 'singbox'),
    'bot': ('telegram-helper-lite', 'telegram-helper'), 'dockhand': ('dockhand',),
}


def control_catalog():
    result = {}
    for descriptor in SERVICE_CATALOG:
        key = descriptor.get('control_component')
        if not key:
            continue
        title, units, containers = result.get(key, (descriptor['display_name'], [], CONTAINER_ALIASES.get(key, ())))
        units = list(dict.fromkeys([*units, *descriptor['unit_candidates']]))
        result[key] = (title, units, containers)
    result['ha'] = ('HA', result['ha'][1], ())
    result['reticulum'][1].extend(['reticulum', 'rnsd'])
    result['dockhand'] = ('Dockhand', [], CONTAINER_ALIASES['dockhand'])
    return result


CONTROL_CATALOG = control_catalog()
